import Head from "next/head";
import { fetchUsers } from "../services/apiUsersList";
import { useEffect, useState } from "react";
import { SearchBox } from "No/components/SearchBox";
import { Pagination } from "No/components/Pagination";

export default function Home() {
  const [users, setUsers] = useState<any>([]);
  const [url, setUrl] = useState("https://fetest.mashx.click/api/users");
  const [prevUrl, setPrevUrl] = useState("");
  const [nextUrl, setNextUrl] = useState("");
  const [currentPage, setCurrentPage] = useState("1");
  const [searchResult, setSearchResult] = useState(users);

  useEffect(() => {
    (async () => {
      const fetchedUsers: any = await fetchUsers(url);
      setUsers([...fetchedUsers.data.data])
      setSearchResult([...fetchedUsers.data.data]);
      setPrevUrl(fetchedUsers.data.prev_page_url);
      setNextUrl(fetchedUsers.data.next_page_url);
      setCurrentPage(fetchedUsers.data.current_page);
    })();
  }, [url]);

  return (
    <>
      <Head>
        <title>L5 Swagger UI</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <SearchBox
          users={users}
          setSearchResult={setSearchResult}
          searchResult={searchResult}
        />
        <div>
          {searchResult.map((user: any) => {
            return (
              <div className="p-2 border-2 border-red-100" key={user.id}>
                <p className="text-lg font-bold">{user.name}</p>
                <p className="text-sm font-medium">{user.email}</p>
              </div>
            );
          })}
        </div>
      </>
      <div className="fixed h-10 bg-white w-full bottom-0">
        <Pagination
          prevUrl={prevUrl}
          nextUrl={nextUrl}
          setUrl={setUrl}
          currentPage={currentPage}
        />
      </div>
    </>
  );
}
