import Head from "next/head";
import { fetchUsers } from "../services/apiUsersList";
import { useEffect, useState } from "react";
import { SearchBox } from "No/components/SearchBox";

export default function Home() {
  const [users, setUsers] = useState<any>([]);

  useEffect(() => {
    (async () => {
      const fetchedUsers: any = await fetchUsers(
        "https://fetest.mashx.click/api/users"
      );
      setUsers([...fetchedUsers?.data.data]);
    })();
  },[]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <SearchBox users={users} />
        <div>
        {users.map((user: any) => {
          console.log(user, "u");
          return (
            <div className="p-2 border-2 border-red-100" key={user.id}>
              <p className="text-lg font-bold">{user.name}</p>
              <p className="text-sm font-medium">{user.email}</p>
            </div>
          );
        })}
      </div>
      </>
    </>
  );
}
